/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.8.3_vite@7.0.5_@t_6e57becbca7d8765dacb0d062c396367/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
